version: '3' 
services:
  app:
    container_name: smartpay_app
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    command: /bin/bash -c "npm start & cd backend && npx nodemon WhatsAppserver.js"
