version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - "4000:4000"
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app/backend
    command: nodemon WhatsAppserver.js
    depends_on:
      - frontend
